### ISSUE TITLE
Composer install before dtp is wiped out by dtp, build steps should be part of dtp workflow

### ISSUE THREAD

**Issue by jazzsequence** [stevector-streaming/dtp#61]
What it says on the tin. When using the `dtp` workflow for https://github.com/jazzsequence/wpnext-test, having a `composer install` step before the `dtp` action would result in the installed artifacts getting wiped out prior to deploy. Instead, I had to pull `dtp` out of the build pipeline to just do a commit after building.

This should be a supported option of the `dtp` workflow: customers who want to `composer install` or `npm install` (or `npm build`) before pushing to Pantheon. Suggest adding an input that toggles build steps in the workflow (or changing the scripts so they do not drop those changes -- I didn't dig into what was happening enough to know why the changes were being dropped).

**Comment by stevector** [comment]
This is why I have a _todo_ in that section of the readme. I haven't tested it https://github.com/stevector-streaming/dtp?tab=readme-ov-file#additional-build-steps-like-composer-install-and-npm-build

I'm hoping that this behavior changes if we make `checkout` a boolean option: https://github.com/stevector-streaming/dtp/blob/0.x/action.yml#L57 Let's try it in our 1:1 today.

**Comment by stevector-streaming** [comment]
I've got it working with my own website using

```
  push-to-pantheon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: "cd web/themes/stevector2024 && npm ci && npm run build"
    - run: "cd web/themes/stevector2024/css && rm .gitignore"
    - name: Deploy to Pantheon
      uses: stevector/push-to-pantheon@checkout_repo
      with:
        ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        machine_token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        site: ${{ vars.PANTHEON_SITE }}
        checkout_repo: false
```

See https://github.com/stevector/push-to-pantheon/pull/2
